### ISSUE TITLE
No props or option for applying custom css on video player.

### ISSUE THREAD

**Issue by shuvo-me** [kingRayhan/react-video-player#1]
![image](https://github.com/kingRayhan/react-video-player/assets/61267686/e12b43e5-2f19-4cf7-8340-7a9b31b0a7b4)

**Comment by kingRayhan** [comment]
Thanks for your suggestion. I will give a prop for className in version `0.1.13`

**Comment by kingRayhan** [comment]
@shuvo-me you can now add className prop including all basic html props like id, ref

https://tsdocs.dev/docs/@graphland/react-video-player/0.1.14/interfaces/VideoPlayerProps.html#className

**Comment by shuvo-me** [comment]
@kingRayhan  great work brother !
